name: GitHub Classroom Workflow

on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: mvn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Upload JaCoCo coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  submit:
    name: Submit to GitHub Classroom
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitHub Classroom Workflow
        uses: education/autograding@v1

